### ISSUE TITLE
print node partitioning information

### ISSUE THREAD

**Issue by zlwu92** [kahypar/mt-kahypar#132]
Hi, I am wondering if mt-kahypar can print out information of each node belongs to which partition into a file?
If yes, where should I add codes or use which execution command parameters. Actually I try to use `--verbose=true --enable-progress-bar=true --partition-output-folder=.` All of them did not give me an output result file.

**Comment by larsgottesbueren** [comment]
Hi,

Try setting --write-partition-file=true. If it still doesn't work, please report back.
At some point the default was changed to not write the file, to avoid spamming files on the user's system. I will update the documentation!

Thanks for pointing this out.

Lars

**Comment by zlwu92** [comment]
I see. This works now. Thank you. 

I want to know in initial partition, I think each node is initialized a partitionID, right? Here you assign 0 or 1 to them at the beginning. Assuming performing a bisection.

Also can we print out how many iterations the coarsen phase have as well as refinement. For each level, can we print out communityID info individually?

**Comment by larsgottesbueren** [comment]
> I see. This works now. Thank you.
> 
> I want to know in initial partition, I think each node is initialized a partitionID, right? Here you assign 0 or 1 to them at the beginning. Assuming performing a bisection.
> 
Correct. But it's on the coarsest (smallest) hypergraph. If you want to have just that partition projected back to the original hypergraph, you can disable the refiners (set `--r-fm-type=do_nothing --r-lp-type=do_nothing`).

> Also can we print out how many iterations the coarsen phase have as well as refinement. For each level, can we print out communityID info individually?

We don't have output for the cluster IDs on each level. The best place to intercept these would be in this line https://github.com/kahypar/mt-kahypar/blob/master/mt-kahypar/partition/coarsening/multilevel_coarsener.h#L251.

As far as I'm aware there's also no counter for the number of coarsening iterations (levels), but you can control it with the `c-max-shrink-factor` parameter. We would get roughly log_{shrink-factor}(n) levels, i.e., the shrink-factor is the base of the log. This is assuming you're using the default config.
If you want just a counter, the same line as above would be the place to increment it.

**Comment by zlwu92** [comment]
> > I see. This works now. Thank you.
> > I want to know in initial partition, I think each node is initialized a partitionID, right? Here you assign 0 or 1 to them at the beginning. Assuming performing a bisection.
> 
> Correct. But it's on the coarsest (smallest) hypergraph. If you want to have just that partition projected back to the original hypergraph, you can disable the refiners (set `--r-fm-type=do_nothing --r-lp-type=do_nothing`).
> 
> > Also can we print out how many iterations the coarsen phase have as well as refinement. For each level, can we print out communityID info individually?
> 
> We don't have output for the cluster IDs on each level. The best place to intercept these would be in this line https://github.com/kahypar/mt-kahypar/blob/master/mt-kahypar/partition/coarsening/multilevel_coarsener.h#L251.
> 
> As far as I'm aware there's also no counter for the number of coarsening iterations (levels), but you can control it with the `c-max-shrink-factor` parameter. We would get roughly log_{shrink-factor}(n) levels, i.e., the shrink-factor is the base of the log. This is assuming you're using the default config. If you want just a counter, the same line as above would be the place to increment it.

What about modifying in deterministic_multilevel_coarsener.cpp? Just add one line `counter++;` in the `coarsenImpl()` method is okay?

**Comment by larsgottesbueren** [comment]
That works as well. Each call to `coarsenImpl()` constitutes a level.
Closing this issue for now. Feel free to re-open if further issues arise or if you have more questions. Always happy to help.
