### ISSUE TITLE
Your system has not enough cpus to execute MT-KaHyPar (> 1)

### ISSUE THREAD

**Issue by gejinhuan** [kahypar/mt-kahypar#135]
I tried to run MT-KaHyPar command. But I received the Error "Your system has not enough cpus to execute MT-KaHyPar (> 1)". Why? My system is WSL, which is a virtual Linux system on Windows 10 Platform.

**Comment by gejinhuan** [comment]
And if I set the number of threads parameter to 2 or greater, it will throw the error
 "terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)"

**Comment by kittobi1992** [comment]
Hi,

Thanks for reaching out to us. We use the hwloc library (only available in Linux) to get information about the underlying hardware topology. As far as I know, the WSL implements most functions of the Linux kernel, but also has some limitations. We have not tested Mt-KaHyPar in this setting yet, but it seems that hwloc is not able to retrieve the required hardware information. What could help is if you share with us the output of `cat /proc/cpuinfo` to see if WSL has correct hardware information.

I also want to mention that support for Windows systems is on our ToDo list, but this may take few months until we release the feature.

**Comment by gejinhuan** [comment]
Thank you for your reply. The output of cat /proc/cpuinfo is as below:
<img width="1906" alt="无标题" src="https://user-images.githubusercontent.com/52098315/220154640-513e0da1-7110-4ad1-8ce9-58bcecf55efb.png">

Can these applications work on virtual Linux system such as Vmware？

**Comment by kittobi1992** [comment]
Your output looks correct. I am not sure if Mt-KaHyPar will work in a virtual environment since we have not tested it yet (probably it will work). However, I will look tomorrow closer into the issue on WSL and hopefully come up with a fix for it.

**Comment by kittobi1992** [comment]
I just setup Windows Subsystem for Linux 2 (WSL2) on my windows machine following these instructions here:
https://pureinfotech.com/install-windows-subsystem-linux-2-windows-10/
I then installed Mt-KaHyPar and was able to run it successfully. Do you use WSL2 or the previous version? If you use the previous version, can you try to upgrade to WSL2 and check if it is working?

**Comment by gejinhuan** [comment]
I used WSL version, not WSL2. I will try to upgrade to WSL2 and try it again, thanks!

**Comment by kittobi1992** [comment]
There a good news. We know have a working windows build on master. If you like, you can try it out and give us feedback :)

**Comment by gejinhuan** [comment]
I update the WSL version to V2. But it still throws the error as below. I think there is nothing to do with WSL.
Is the command which I typed right?
I can not find the working windows build on master. Can you give me a link? Thanks!!!![Uploading 截屏2023-02-25 下午11.42.11.png…]()

**Comment by gejinhuan** [comment]
I update the WSL version to V2. But it still throws the error as below. I think there is nothing to do with WSL.
Is the command which I typed right?
I can not find the working windows build on master. Can you give me a link? Thanks!!!
![Uploading 截屏2023-02-25 下午11.42.11.png…]()

**Comment by gejinhuan** [comment]
I update the WSL version to V2. But it still throws the error as below. I think there is nothing to do with WSL.
Is the command which I typed right?
I can not find the working windows build on master. Can you give me a link? Thanks!!!
![截屏2023-02-25 下午11 42 11](https://user-images.githubusercontent.com/52098315/221389281-231ad4dd-7884-48c6-99f2-9e9b9372d50f.png)

**Comment by kittobi1992** [comment]
The command looks correct. It seems that there is some issue with your machine and WSL. To build Mt-KaHyPar on Windows, you have to clone the git repository and follow the build instructions in our README.

**Comment by gejinhuan** [comment]
I tried to build it on native Linux platform and it can work normally now.  Maybe there was something wrong with my WSL system. Thank you very much.

**Comment by kittobi1992** [comment]
I am happy to hear that you were able to compile and run Mt-KaHyPar :) If you have any further questions, do not hesitate to contact us.
