### ISSUE TITLE
How to build this if my TBB is installed in my user customized path?

### ISSUE THREAD

**Issue by zlwu92** [kahypar/mt-kahypar#143]
I build TBB from source and install it under my user home directory, let's say /home/xxx/tbb/include and /home/xxx/tbb/lib64. And I also add this two path into my ~/.bashrc file append after variable PATH and LD_LIBRARY_PATH. Then I source this file also. 

But when I build mt-kahypar with cmake .., it still shows cannot find TBB package. How should I solve it?

Btw, my gcc version is 12.0

**Comment by larsgottesbueren** [comment]
Try setting the `TBB_ROOT` environment variable to your installation path and then do a fresh invocation of cmake. This will tell the script at `cmake/modules/FindTBB.cmake` where to look for your tbb installation. Starting at line 32 there's a couple more hints if it doesn't work right away.

If that doesn't work, we also offer the option to download and build tbb automatically via the `KAHYPAR_DOWNLOAD_TBB` variable; set it to `ON`.

**Comment by zlwu92** [comment]
you mean export TBB_ROOT=/home/xxx/tbb/include:$TBB_ROOT in my bashrc ？

**Comment by larsgottesbueren** [comment]
Did you get it to compile successfully? If so, please feel free to mark the issue as resolved.
