### ISSUE TITLE
glibc++.so.6 version

### ISSUE THREAD

**Issue by zlwu92** [kahypar/mt-kahypar#144]
![image](https://user-images.githubusercontent.com/104770161/232653657-9c8934c5-c11f-45fd-b47b-b222a819cf6d.png)
Hi,

When I build and compile, I run mt-kahypar executable, I got this runtime error. I have no root access, how could I change its system link to my user path which I prepare a 30 higher version library.

**Comment by larsgottesbueren** [comment]
Did you compile gcc yourself as well? If so, you will have to set the appropriate glibc version.
Try `export LD_LIBRARY_PATH=/gcc/trunk/x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs/` with the appropriate path to your compiler location.

**Comment by zlwu92** [comment]
I use the gcc already provided by the HPC system, which is gcc-12 I think. I do not compile and reinstall it from source by myself.

**Comment by zlwu92** [comment]
Yes I can. I think it because my system (Ubuntu22.04) libraries like GLIBCXX_ has updated version for example 3.4.30. In HPC environment they use the RedHat system which maintains old libraries for a very long time. They will not update it frequently for the purpose of system stability.

**Comment by larsgottesbueren** [comment]
Well, we don't depend on specific glibc versions ourselves. These are set by the compiler you use.
