### ISSUE TITLE
hmod.precompute_attributes removes or does not remove singletons based off of the OS (inconsistent behaviour)

### ISSUE THREAD

**Issue by Leo-Aus-Berlin** [kahypar/mt-kahypar#149]
### Depending on which OS is being used the following will print different results:

```
import hypernetx as hnx
import hypernetx.algorithms.hypergraph_modularity as hmod
formulaDict,stringTree = readFile("./CDL-FMINCE/toybox.dimacs") # code by me
H=formulaToHypergraph(formulaDict)
HDual = H.dual()
H=hmod.precompute_attributes(H)
HDual = hmod.precompute_attributes(HDual)

#this should diverge based off of OS

print(len(list(H.nodes())))
print(len(list(HDual.nodes())))
```

On the linux systems the results are 544 and 590, while on Windows I get 175 and 221.

I was using ANTLR4 with python integration to parse a dimacs (SAT) file and interpret it as a hypergraph. The resulting graph has 544 nodes and 590 edges before the attributes are computed.

# Compared Systems

Ubuntu system:
- Ubuntu 20.04.6 LTS
- wsl 2
- Python 3.8.10
- pip installation manager

Debian
-  SMP Debian 5.10.127-1
- Python 3.9.2
- pip installation manager

Windows
- Windows 10 Home
- Python 3.11.3
- Anaconda virtual environment (+VSCode)

**Comment by larsgottesbueren** [comment]
This doesn't look like it's related to mt-kahypar.

**Comment by Leo-Aus-Berlin** [comment]
Oops. Wrong Git-Repo Tab.
My sincerest Apologies...
