### ISSUE TITLE
make mtkahypar fatal error "utils/debug.hpp: no such file or directory"

### ISSUE THREAD

**Issue by danieljmg** [kahypar/mt-kahypar#154]
Dear developers,

Under Ubuntu 23.04 and GCC 13.2 I am getting the following fatal error after running make mtkahypar:
 
```

In file included from /home/X/Documents/mt-kahypar/external_tools/growt/data-structures/table_config.hpp:6,

                 from /home/X/Documents/mt-kahypar/mt-kahypar/partition/mapping/target_graph.h:40,

                 from /home/X/Documents/mt-kahypar/lib/libmtkahypar.cpp:39:

`/home/X/Documents/mt-kahypar/external_tools/growt/data-structures/element_types/complex_slot.hpp:8:10: fatal error: utils/debug.hpp: No such file or directory

    8 | #include "utils/debug.hpp"
      |          ^~~~~~~~~~~~~~~~~


```

Any hint of what could have been happening?

Thank you in advance.

**Comment by kittobi1992** [comment]
Hello @danieljmg,

we recently added the submodule growt that depends also on other submodules. The command for checking out our submodules in our Readme only initializes growt but not the submodules of growt. I will tomorrow update the README with the right command.

What you could do in the meantime is to checkout the submodules of growt manually. You have to go to the directory external_tools/growt and run 'git submodule init' and 'git submodule update'.

Thank you for pointing this out and let me know if the fix works for you.

Best,
Tobias

**Comment by danieljmg** [comment]
> Hello @danieljmg,
> 
> we recently added the submodule growt that depends also on other submodules. The command for checking out our submodules in our Readme only initializes growt but not the submodules of growt. I will tomorrow update the README with the right command.
> 
> What you could do in the meantime is to checkout the submodules of growt manually. You have to go to the directory external_tools/growt and run 'git submodule init' and 'git submodule update'.
> 
> Thank you for pointing this out and let me know if the fix works for you.
> 
> Best, Tobias

It works perfectly now.
Some interesting insights:

- Tested on Ubuntu 23.10 (nigthly) x86_64 with GCC version 13.2.
- Added the following compiler optimisation flags, which are above the existing ones like -O3, to CMAKELIST and they work perfectly: 
```
set(CMAKE_CXX_FLAGS_RELEASE "-Ofast -flto=auto -pipe -fopenmp -D_GLIBCXX_PARALLEL")
set(CMAKE_CXX_FLAGS_DEBUG "-Ofast -flto=auto -pipe -fopenmp -D_GLIBCXX_PARALLEL")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-Ofast -flto=auto -pipe -fopenmp -D_GLIBCXX_PARALLEL")

```
Thank you,
Best regards.

**Comment by kittobi1992** [comment]
Hi @danieljmg,

we haven't tested the 64-bit node ID mode for a while now since for most of our use cases 32-bit node IDs are enough to represent almost all hypergraphs that fit into the main memory of a single machine. I would recommend do use the 32-bit mode since Mt-KaHyPar is then significantly faster. Do you have an use case that requires 64-bit node IDs?

**Comment by danieljmg** [comment]
> Hi @danieljmg,
> 
> we haven't tested the 64-bit node ID mode for a while now since for most of our use cases 32-bit node IDs are enough to represent almost all hypergraphs that fit into the main memory of a single machine. I would recommend do use the 32-bit mode since Mt-KaHyPar is then significantly faster. Do you have an use case that requires 64-bit node IDs?

Not at the moment. I just wanted to share it with you.
I consider the issue solved.
Thank you for the fast answers and fix.
