### ISSUE TITLE
Upper bound of cut between two blocks

### ISSUE THREAD

**Issue by yumi-di** [kahypar/mt-kahypar#156]
Hi,
Is there a data structure that records the total cuts between two blocks? 
I want to avoid a very large cut between the two blocks after the partition. So I want to get the total cut value between each two blocks dynamically, and modify the gain function according to this cut.

In other words, I hope to optimize the cut objective while keeping the total cut between blocks within the upper bound. Is there any way to deal with this situation?

thanks!

**Comment by kittobi1992** [comment]
Hi @yumi-di,

I assume that you are using our interface for plugin new objective function and want to minimize something like the max_{i,j} cut(V_i, V_j) - in other words, the maximum cut running between any two blocks.

At the moment, we do not maintain the cut between two blocks, but it should be not that hard to add that feature. I would first implement a class that maintains the cut size between each block and then add that class as a member to our PartitionedGraph and PartitionedHypergraph class. You can then update the data structure when you move a node (see changeNodePart). To pass the data structure to our gain computation techniques, you can add a pointer to our `SyncronizedEdgeUpdate` struct:
https://github.com/kahypar/mt-kahypar/blob/master/mt-kahypar/datastructures/hypergraph_common.h#L142

You can set the pointer when you move a node (similar to the `target_graph` member):
https://github.com/kahypar/mt-kahypar/blob/master/mt-kahypar/datastructures/partitioned_hypergraph.h#L596

Note that when you optimize the objective function, refinement algorithm should focus on the block pair with the largest cut size. However, our current refinement algorithms do not implement that efficiently. This could lead to slow convergence and you should think also of implementing specialized refinement algorithms for this objective function.

If you have any further questions do not hesitate to contact us.

Best

**Comment by yumi-di** [comment]
Thanks a lot for your reply! I am trying to implement this feature.

Also, I would like to know if there is a simple way to support multiple resources? Similar to this issue：https://github.com/kahypar/kahypar/issues/126 

After the partitioning is done, I hope that each kind of resource in the block will not exceed the limit. In my cases, except for one most critical resource, the limit of other kinds of resources is very loose, to illustrate with "imbanlance", the imbalance of a key resource is 0.1~0.2, and the imbalance of other resources is 4 or more. It is acceptable for the cut obj to become worse.

Can I simply change the "HypernodeWeight" data structure to an array-based one? Or is there any other way? 

Thanks!

**Comment by larsgottesbueren** [comment]
As you pointed out, the best way to implement this is to turn the scalar weight into a d-dimensional vector per node. The balance-preservation check for vertex moves becomes a bit more involved to do correctly in the parallel setting (atomically), but it's still possible to do.

If you're not in a hurry, we will add official support for multi-constraint partitioning in the future. Just today, we recruited a new student to work on this, who will start in October. My current estimate is that the basic version with the current refinement algorithms will land in about two months.
