### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by uulm-janbaudisch** [kahypar/mt-kahypar#172]
Currently, only Linux and Windows systems seem to be supported. Would it be possible to also support macOS and/or reduce the amount of platform-specific code so that it might compile with any C++ compiler?

**Comment by kittobi1992** [comment]
Just saw the issue after I implemented the macOS build today :D I already merged it to master. However, it is not properly tested and needs some follow-up changes. It works on my machine and in the CI. Let me know when you discover any issues with the build.

**Comment by uulm-janbaudisch** [comment]
Great, I will try it out. Thank you!
