### ISSUE TITLE
Static library

### ISSUE THREAD

**Issue by uulm-janbaudisch** [kahypar/mt-kahypar#173]
As I closed the original merge request (#161), I wanted to leave it open as an issue at least.
The intend was to make it possible to build the library as a static version. Currently, this is not possible as the static version behaves differently at runtime, resulting in some values being not initialized: https://github.com/kahypar/mt-kahypar/pull/161#issuecomment-1774143147

It would be great if the possibility to build a static library was there. In our use case, we are using Mt-KaHyPar for a Rust project and the Rust ecosystem is usually bundling dependencies as static versions so that the result is a single binary which also makes distribution easier. However, the downside might be that TBB is not supposed to be built statically.

**Comment by N-Maas** [comment]
@uulm-janbaudisch You might be interested to hear that we have now full support for static builds when building boost and TBB from source (see #199, `KAHYPAR_STATIC_LINK_DEPENDENCIES` and `KAHYPAR_STATIC_LINK_TBB` flags). Although you might need to disable the `hwloc` dependency if you want to build a shared object.

Note that there are some small changes to the C interface and it is likely that there will be additional breaking changes before we officially release the next version.
