### ISSUE TITLE
Segmentation fault during partitioning

### ISSUE THREAD

**Issue by DanielSeemaier** [kahypar/mt-kahypar#178]
Running the current version from `main` with these arguments:

```
taskset -c 0-63 /.../disk-MtKaHyPar-latest- -h /.../rgg27_3d.graph --input-file-format=metis -k 16 -e 0.03 --seed=1 -t 64 --instance-type=graph --preset-type=default -o cut
```

sometimes (edit: very rarely, two runs out of ~600) crashes with a segmentation fault:

```
******************************************************************************** 
*                               Local Search...                                * 
******************************************************************************** 
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
```

Full output log:  [MtKaHyPar.crash.log](https://github.com/kahypar/mt-kahypar/files/13952205/MtKaHyPar.crash.log)

**Comment by kittobi1992** [comment]
Is anyone investigating this problem? Looks like a problem with `tbb::cocurrent_vector`

**Comment by DanielSeemaier** [comment]
Yeah, might be my bad, we're currently waiting for new results :)

**Comment by larsgottesbueren** [comment]
Is it working fine with the ```DOWNLOAD_TBB``` option now? Maybe we should just turn it on by default?

**Comment by DanielSeemaier** [comment]
Yes, that was indeed the issue. I had the flag set but ran the CMake command from outside the build directory, which caused the CMake script to download TBB to the wrong directory (current working directory). This should be fixed, but is a separate issue.
