### ISSUE TITLE
performing V-cycle with a initial partition

### ISSUE THREAD

**Issue by chenmagi** [kahypar/mt-kahypar#179]
Hi,

I noticed the difference in functionality between KaHyPar and Mt-KaHyPar regarding the V-cycle interface in Python.  Do you have a plan to enable that feature?

**Comment by larsgottesbueren** [comment]
Hi Magi,

You should be able to set the number of V-cycles in the context object (which passes options to the solver). If that doesn't work (please let us know), you can use the ```improvePartition``` function. It takes the number of V-cycles as an argument directly, i.e., you could first call the partitioner as you already do and then call improvePartition directly after with the desired number of cycles.

Hope this helps and if you have any further questions, please follow up.

Lars

**Comment by chenmagi** [comment]
Hi Lars,

  Thank you for the comment. I found the example and used the API in my project. It works.
