### ISSUE TITLE
If the parallel implementation uses SIMD instruction

### ISSUE THREAD

**Issue by zlwu92** [kahypar/mt-kahypar#182]
Hi,

I feel this is a great project. And I'm wondering if this framework utilizes SIMD instruction for parallelization or the multithreaded CPU program? (For example, the deterministic version of mt-kahypar)

**Comment by larsgottesbueren** [comment]
We're not using SIMD (beyond what the compiler auto-vectorizes). Our algorithms exhibit sparse random memory access patterns to gather and aggregate data, which to my understanding is not well suited for SIMD. Additionally, there's no heavy arithmetic in performance-critical sections.

We're always open to learn about more ways to improve performance in our code. If you have cool ideas how to use SIMD in a partitioning code, we'd love to hear about them!

Please feel free to reopen the issue, if I haven't adequately addressed your question.

Lars
