### ISSUE TITLE
[Python] About Thread Pool

### ISSUE THREAD

**Issue by luojw-dwr** [kahypar/mt-kahypar#187]
Using the python interface, how can I release the threads allocated by `mtkahypar.initializeThreadPool(...)`?

**Comment by kittobi1992** [comment]
Hi @luojw-dwr,

This is a good question. We currently do not have any interface function to destruct the internal thread pool of `tbb`. The `initializeThreadPool` function constructs the `tbb::global_control` object that defines maximum available parallelism. However, I don't think it is responsible for creating the threads. This will be handled by TBB task scheduler internally. The threads currently live as long as the python module is loaded. However, idling threads do not consume any CPU and their memory footprint should be also fairly small. Modern OS should also be able to handle a large amount of inactive threads nowadays.

Is there any concern that you have if these threads are not released in your application?

Best,
Tobias

**Comment by luojw-dwr** [comment]
Hi @kittobi1992

Thanks for your time and reply. I am using `mtkarhypar` in a shared environment which sets a hard limitation to the number of user threads. The problem happens when the python program incorporates with other libraries (such as `python-mip`) that has another thread pool, thus summing up the overall threat count beyond the hard limit.

As a workaround, I may separate the partitioning part of my program to a standalone process. But it would be cool if the thread pool can be temporarily destructed, and later on `initializeThreadPool` again if needed.

Thank you again for your warm reply.

**Comment by kittobi1992** [comment]
Hi @luojw-dwr,

Just found out that it is possible to terminate the TBB worker threads:
https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onetbb/source/task_scheduler/scheduling_controls/task_scheduler_handle_cls

I will try to integrate it by the end of the week.

Best,
Tobias

**Comment by kittobi1992** [comment]
Opened a PR that allows terminating the TBB thread pool via a library function. However, our CI is currently not working with the change since it requires oneTBB 2021.6 but you can use the branch for internal testing.

**Comment by luojw-dwr** [comment]
Hi @kittobi1992
Tried this version with debug build, `import mtkahypar` causes a segmentation fault immediately, with no debug info printed.

**Comment by luojw-dwr** [comment]
Hi @kittobi1992 

Would please share your compilers and dependency versions? Especially compiler and `TBB`. Thank you.

**Comment by luojw-dwr** [comment]
Hi @kittobi1992 
I found the reason for the segmentation fault. In `python/module.cpp`, it should be:
```
bool terminate_thread_pool() {
  return mt_kahypar::TBBInitializer::instance().terminate();
}
```
rather than:
```
bool terminate_thread_pool() {
  mt_kahypar::TBBInitializer::instance().terminate();
}
```
(notice the missing `return`). Surprisingly it could pass the compilation.

**Comment by kittobi1992** [comment]
Hi @luojw-dwr, 
Sorry for my late response and thanks for investigating the issue by your own. I have currently not setup the python build on my Mac and relied on the CI which does not pass at the moment (see comments in PR). I will try to make it work tomorrow, and get the change merged.

Also good to hear that it is working for you.

Best,
Tobias
