### ISSUE TITLE
make python lib interface Error

### ISSUE THREAD

**Issue by chfissogoodman** [kahypar/mt-kahypar#194]
When I use make mtkahypar_python, there is an error after [100%] Linking CXX shared module mtkahypar.cpython-312-x86_64-linux-gnu.so, the error is as follows, Is there any way to solve it? I compiled it on the server. I don't have admin rights.
[100%] Linking CXX shared module mtkahypar.cpython-312-x86_64-linux-gnu.so
lto-wrapper: warning: using serial compilation of 128 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
/usr/bin/ld: ../libmini_boost.a(cmdline.cpp.o): warning: relocation against `_ZTVN5boost15program_options33too_many_positional_options_errorE' in read-only section `.text._ZN5boost16exception_detail19error_info_injectorINS_15program_options33too_many_positional_options_errorEEC2ERKS4_[_ZN5boost16exception_detail19error_info_injectorINS_15program_options33too_many_positional_options_errorEEC5ERKS4_]'
/usr/bin/ld: ../libmini_boost.a(cmdline.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN5boost6detail15sp_counted_base7destroyEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[3]: *** [python/CMakeFiles/mtkahypar_python.dir/build.make:1453: python/mtkahypar.cpython-312-x86_64-linux-gnu.so] Error 1
make[2]: *** [CMakeFiles/Makefile2:1477: python/CMakeFiles/mtkahypar_python.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1484: python/CMakeFiles/mtkahypar_python.dir/rule] Error 2
make: *** [Makefile:582: mtkahypar_python] Error 2

**Comment by N-Maas** [comment]
Hi @chfissogoodman,

you should be able to fix the error by adding `-DCMAKE_POSITION_INDEPENDENT_CODE=On` to the `cmake` command and building again.

**Comment by chfissogoodman** [comment]
Thanks so much
