### ISSUE TITLE
About 'PresetType. DETERMINISTIC' use error problem

### ISSUE THREAD

**Issue by chfissogoodman** [kahypar/mt-kahypar#197]
Hello,

I'm currently using context.loadPreset(mtkahypar.PresetType.DETERMINISTIC) in combination with hypergraph.mapOntoGraph(graph, context), but this leads to a segmentation fault (core dumped) error. Interestingly, this issue doesn’t occur when using the DEFAULT or QUALITY presets instead.

Could you please help me understand why this might be happening? I would appreciate any guidance on whether this is due to compatibility issues, specific requirements of the DETERMINISTIC mode, or if there might be other factors involved.

Thank you very much for your time and assistance!

**Comment by larsgottesbueren** [comment]
It's unclear, but this may be a compatibility issue. At what stage of the algorithm does the crash occur? (Coarsening, initial mapping, refinement). Can you please share your mt-kahypar call.

**Comment by N-Maas** [comment]
I can reproduce a crash when adding an according call to the interface tests:
```
[all_pair_shortest_path.cpp:42:compute]: Assertion `static_cast<size_t>(n * n) <= distances.size()` failed
```
I should have some time to look into it today.

**Comment by chfissogoodman** [comment]
I'm sorry, I'm not quite sure what you mean. I'm now calling the library in python, and I'm converting the hypergraph to hmetis format, converting the graph to metis format, and then calling it with the following code.：
def partition_hypergraph(k, node_id_map,hypergraph_file,graph_file):
    mtkahypar.initializeThreadPool(4) 
    context = mtkahypar.Context()
    context.loadPreset(mtkahypar.PresetType.DETERMINISTIC) 
    context.setPartitioningParameters(
        k,                        
        0.03,                     
        mtkahypar.Objective.CUT
  
    )
    mtkahypar.setSeed(42)          
    context.logging = True         
    hypergraph = mtkahypar.Hypergraph(
        hypergraph_file, 
        mtkahypar.FileFormat.HMETIS  
    )
 
    graph = mtkahypar.Graph(
        graph_file, 
        mtkahypar.FileFormat.METIS  
    )

  
    partitioned_hg = hypergraph.mapOntoGraph(graph, context)
    return partitioned_hg

**Comment by chfissogoodman** [comment]
![1](https://github.com/user-attachments/assets/0697ebda-c584-496e-9bff-05b5a0537b0a)

**Comment by N-Maas** [comment]
Hi @chfissogoodman,

could you try whether the changes on branch `nikolai/steiner-trees-fix` fix your problem?

**Comment by chfissogoodman** [comment]
thanks ！it works
