### ISSUE TITLE
Non-Deterministic Results while using binary

### ISSUE THREAD

**Issue by LeaveryF** [kahypar/mt-kahypar#198]
Hello.

When I use mtkahypar with c library, I also met the problem of "Non-Deterministic Results", as is shown in #190 and #189 . Then I switched from c library to binary. However, this problem still exists.

This is how I run mtkahypar binary:
```bash
./MtKaHyPar \
  -h mt_input_hypergraph.txt \
  --preset-type=deterministic \
  -t 4 \
  -k 8 \
  -e 0.03 \
  -g mt_input_target_graph.txt \
  -o steiner_tree \
```
where mt_input_hypergraph.txt and mt_input_target_graph.txt are generated by my project.

And this is the different results:
```plaintext
Objectives: 
  steiner_tree         = 1136 (primary objective function) 
  Approximation Factor = 1.00484  
  cut                  = 931  
  km1                  = 1116  
  soed                 = 2047  
  Imbalance            = 0.0288922  
  Partitioning Time    = 0.161263 s  

Partition sizes and weights:  
|block 0| =  103  w( 0 ) = 5247  max( 0 ) = 5597
|block 1| =   37  w( 1 ) = 5591  max( 1 ) = 5597
|block 2| =   88  w( 2 ) = 5389  max( 2 ) = 5597
|block 3| =  100  w( 3 ) = 5381  max( 3 ) = 5597
|block 4| =   87  w( 4 ) = 5391  max( 4 ) = 5597
|block 5| =   86  w( 5 ) = 5400  max( 5 ) = 5597
|block 6| =   39  w( 6 ) = 5482  max( 6 ) = 5597
|block 7| =   60  w( 7 ) = 5589  max( 7 ) = 5597
```
```plaintext
Objectives: 
  steiner_tree         = 1135 (primary objective function) 
  Approximation Factor = 1.00484  
  cut                  = 931  
  km1                  = 1116  
  soed                 = 2047  
  Imbalance            = 0.0288922  
  Partitioning Time    = 0.162108 s  

Partition sizes and weights:  
|block 0| =   60  w( 0 ) = 5589  max( 0 ) = 5597
|block 1| =   39  w( 1 ) = 5482  max( 1 ) = 5597
|block 2| =  100  w( 2 ) = 5381  max( 2 ) = 5597
|block 3| =   87  w( 3 ) = 5391  max( 3 ) = 5597
|block 4| =   88  w( 4 ) = 5389  max( 4 ) = 5597
|block 5| =  103  w( 5 ) = 5247  max( 5 ) = 5597
|block 6| =   37  w( 6 ) = 5591  max( 6 ) = 5597
|block 7| =   86  w( 7 ) = 5400  max( 7 ) = 5597
```

Also, it seems that the larger the scale of the (hyper)graph file, the more likely and clearly the results will differ.

Interestingly, when I use instances in mtkahypar project, for example, the ibm01.hgr and target.graph, this problem didn't occur. So, it seems the problem lies in my (hyper)graph file?

I have no idea what I should do. If you want my (hyper)graph files, I'm willing to offer them.

**Comment by LeaveryF** [comment]
Just now, I tested ibm01.hgr along with my target graph file. That means I changed target graph file from target.graph in your project to mine. Then this problem occurred again. 

My target graph files are as follows:
```plaintext
4 3 1
2 1 
1 1 3 1 
2 1 4 1 
3 1 

```
or
```plaintext
8 11 1
2 1 5 1 7 1 
1 1 3 1 6 1 7 1 
2 1 8 1 
8 1 
1 1 6 1 
2 1 5 1 7 1 
1 1 2 1 6 1 8 1 
3 1 4 1 7 1 

```
Both of them, as the mapped graph file, have the non-deterministic problem.

Did I write the target graph file incorrectly or are there some other reasons for this?

**Comment by N-Maas** [comment]
Hi @LeaveryF,

thanks for the detailed report! You probably did nothing wrong and there is actually an issue with the algorithm. I'm afraid support for steiner trees is still a bit experimental, specifically with regards to the deterministic configuration.

From the results you showed, it seems that the main partitioning step is deterministic, however the mapping to the target graph is different in both cases. Therefore, the most likely cause is that some part of the mapping procedure is not deterministic. I will try to investigate it this week and see whether I can fix the problem.

**Comment by N-Maas** [comment]
Could you check out whether the branch `nikolai/deterministic-mapping` fixes the problem @LeaveryF ?

**Comment by LeaveryF** [comment]
Mapping to small target graph, such as the two files above, the results have been stable, but larger target graph still have this problem.
Here is another graph file with which I met the problem:
```plaintext
32 88 1
13 1 15 1 19 1 28 1 30 1 
5 1 9 1 14 1 23 1 29 1 
16 1 18 1 21 1 26 1 32 1 
12 1 20 1 21 1 22 1 25 1 
2 1 7 1 12 1 13 1 
12 1 13 1 21 1 23 1 24 1 30 1 
5 1 11 1 21 1 23 1 26 1 
11 1 14 1 16 1 18 1 23 1 26 1 27 1 
2 1 16 1 21 1 31 1 
18 1 20 1 21 1 28 1 31 1 32 1 
7 1 8 1 12 1 26 1 30 1 32 1 
4 1 5 1 6 1 11 1 22 1 23 1 25 1 28 1 
1 1 5 1 6 1 19 1 25 1 
2 1 8 1 16 1 23 1 25 1 
1 1 20 1 25 1 
3 1 8 1 9 1 14 1 20 1 21 1 24 1 26 1 28 1 
20 1 24 1 26 1 27 1 
3 1 8 1 10 1 24 1 30 1 
1 1 13 1 
4 1 10 1 15 1 16 1 17 1 21 1 24 1 32 1 
3 1 4 1 6 1 7 1 9 1 10 1 16 1 20 1 24 1 27 1 
4 1 12 1 23 1 31 1 
2 1 6 1 7 1 8 1 12 1 14 1 22 1 30 1 
6 1 16 1 17 1 18 1 20 1 21 1 28 1 
4 1 12 1 13 1 14 1 15 1 
3 1 7 1 8 1 11 1 16 1 17 1 30 1 32 1 
8 1 17 1 21 1 
1 1 10 1 12 1 16 1 24 1 29 1 
2 1 28 1 
1 1 6 1 11 1 18 1 23 1 26 1 31 1 
9 1 10 1 22 1 30 1 
3 1 10 1 11 1 20 1 26 1 

```
It does happen more rarely. Using test_instance.hgr in your project and my target graph file can reproduce this problem, maybe.

**Comment by N-Maas** [comment]
Okay, I found another bug which was a bit more tricky and actually affected the non-deterministic mode, too. Could you try again with the new commit @LeaveryF ?

Also, the issue that I found implies that the steiner trees only work for k <= 64 for now. Is this a problem for your use case? With some additional work it would be possible to allow larger k. Note however that the running time might degrade for large k anyways due to the high computational complexity of the steiner tree metric.

**Comment by LeaveryF** [comment]
It works well in my cases now. Thank you very much.

And, my use case just need k <= 64, so that's not a problem for me now.

**Comment by LeaveryF** [comment]
Hi, I have another question. It's small and not so important. In deterministic preset type, do the c library interfaces "mt_kahypar_create_hypergraph" and "mt_kahypar_read_hypergraph_from_file" construct the same hypergraph? I have tried both, but they seem different.

**Comment by N-Maas** [comment]
Could you specify what you mean with "seem different"? If the data in the file and the data provided to `mt_kahypar_create_hypergraph` are equivalent and you are using deterministic preset, they should result in the same hypergraph.

Note that you need to be a bit careful with the input to `mt_kahypar_create_hypergraph`, specifically you need to provide a sentinel element as the last entry in `hyperedge_indices` (see example in the header file). At the moment, we don't have checks for the validity of the input.

**Comment by LeaveryF** [comment]
Well, I have some raw hypergraph data, and I have tried to process it in different ways...

In the first time, I read the data and transformed it into my data structure, then used `mt_kahypar_create_hypergraph` to construct the hypergraph. And then, started partition.

In the second time, I processed the data into an hmetis file, then used `mt_kahypar_read_hypergraph_from_file` to construct the hypergraph. And then, started partition.

In the third time, I processed the data into an hmetis file, then used mt binary to process the hypergraph.

All of them were set the same imbalance, seed, and deterministic preset type, along with the same steiner tree mapped target graph.

The results(steiner tree metric, and final partition results) for 2 and 3 are the same, which I think that means the problem does not lie in partition process. While 1 is different from them, which I personally think the problem may lie in this c library interface.

I think I followed the input format of `mt_kahypar_create_hypergraph` and it does have the sentinel element. I will also review it again and test different data later.

**Comment by LeaveryF** [comment]
I found that mapping `./tests/instances/hypergraph_with_node_and_edge_weights.hgr` to target graph `./tests/interface/test_instances/target.graph` or `./tests/instances/graph_with_edge_weights.graph` would cause a Segmentation fault during Initial Partitioning. Is that normal?

This is the params:
```bash
./build/mt-kahypar/application/MtKaHyPar \
  -h ./tests/instances/hypergraph_with_node_and_edge_weights.hgr \
  --preset-type=deterministic \
  -t 4 \
  -k 8 \
  -e 0.03 \
  -g ./tests/instances/graph_with_edge_weights.graph \
  -o steiner_tree \
```

**Comment by LeaveryF** [comment]
OK, I see it! Thank you.
